# Generated by Django 5.0.6 on 2024-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_vendas',
            field=models.IntegerField(),
        ),
    ]
